#include "output/blender.h"
#include "filters/subpixel_filter.h"
#include "color_math.h"
#include "config.h"

#include <cmath>
#include <algorithm>
#include <vector>

namespace puretype
{
    Blender& Blender::Instance()
    {
        static Blender instance;
        return instance;
    }

    void Blender::PremultiplyAlpha(uint8_t* bgra, int width, int height, int pitch)
    {
        for (int y = 0; y < height; ++y)
        {
            uint8_t* row = bgra + y * pitch;
            for (int x = 0; x < width; ++x)
            {
                uint8_t* px = row + x * 4;
                uint8_t a = px[3];
                if (a == 0)
                {
                    px[0] = px[1] = px[2] = 0;
                }
                else if (a < 255)
                {
                    px[0] = static_cast<uint8_t>((px[0] * a + 127) / 255);
                    px[1] = static_cast<uint8_t>((px[1] * a + 127) / 255);
                    px[2] = static_cast<uint8_t>((px[2] * a + 127) / 255);
                }
            }
        }
    }

    bool Blender::BlitToHDC(HDC hdc, int x, int y,
                            const RGBABitmap& bitmap,
                            COLORREF textColor,
                            float gamma)
    {
        (void)gamma; // Il Gamma shaping è già gestito in SubpixelFilter / ToneMapper
        if (bitmap.data.empty() || bitmap.width <= 0 || bitmap.height <= 0) return false;

        // Colore del testo desiderato in spazio lineare
        float linTextR = sRGBToLinear(GetRValue(textColor));
        float linTextG = sRGBToLinear(GetGValue(textColor));
        float linTextB = sRGBToLinear(GetBValue(textColor));

        BITMAPINFO bmi = {};
        bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
        bmi.bmiHeader.biWidth = bitmap.width;
        bmi.bmiHeader.biHeight = -bitmap.height; // Top-down
        bmi.bmiHeader.biPlanes = 1;
        bmi.bmiHeader.biBitCount = 32;
        bmi.bmiHeader.biCompression = BI_RGB;

        void* dibBits = nullptr;
        HDC memDC = CreateCompatibleDC(hdc);
        if (!memDC) return false;

        HBITMAP hBitmap = CreateDIBSection(memDC, &bmi, DIB_RGB_COLORS, &dibBits, nullptr, 0);
        if (!hBitmap || !dibBits)
        {
            DeleteDC(memDC);
            return false;
        }

        HGDIOBJ oldBitmap = SelectObject(memDC, hBitmap);
        if (!oldBitmap)
        {
            DeleteObject(hBitmap);
            DeleteDC(memDC);
            return false;
        }

        // Copia lo sfondo attuale di Windows nel nostro buffer DIB
        BitBlt(memDC, 0, 0, bitmap.width, bitmap.height, hdc, x, y, SRCCOPY);

        uint8_t* dst = static_cast<uint8_t*>(dibBits);
        int dstPitch = bitmap.width * 4;

        // SUBPIXEL BLENDING: Apply the R/G/B coverage mask generated by the filter pipeline.
        for (int row = 0; row < bitmap.height; ++row)
        {
            const uint8_t* srcRow = bitmap.data.data() + row * bitmap.pitch;
            uint8_t* dstRow = dst + row * dstPitch;

            for (int col = 0; col < bitmap.width; ++col)
            {
                const uint8_t* srcPx = srcRow + col * 4;
                uint8_t* dstPx = dstRow + col * 4;

                if (srcPx[3] == 0) continue; // Salta i pixel vuoti per massimizzare le performance

                // La nostra maschera di copertura subpixel in spazio lineare
                float maskB = sRGBToLinear(srcPx[0]);
                float maskG = sRGBToLinear(srcPx[1]);
                float maskR = sRGBToLinear(srcPx[2]);

                // Lo sfondo preesistente in spazio lineare
                float bgB = sRGBToLinear(dstPx[0]);
                float bgG = sRGBToLinear(dstPx[1]);
                float bgR = sRGBToLinear(dstPx[2]);

                // Fusione subpixel perfetta (Alpha Blending separato per canale)
                float finalB = bgB * (1.0f - maskB) + linTextB * maskB;
                float finalG = bgG * (1.0f - maskG) + linTextG * maskG;
                float finalR = bgR * (1.0f - maskR) + linTextR * maskR;

                dstPx[0] = linearToSRGB(finalB);
                dstPx[1] = linearToSRGB(finalG);
                dstPx[2] = linearToSRGB(finalR);
            }
        }

        BOOL blitResult = BitBlt(hdc, x, y, bitmap.width, bitmap.height, memDC, 0, 0, SRCCOPY);

        SelectObject(memDC, oldBitmap);
        DeleteObject(hBitmap);
        DeleteDC(memDC);

        return blitResult != FALSE;
    }

    bool Blender::BlitToD2DTarget(ID2D1RenderTarget* pRT, float x, float y,
                                  const RGBABitmap& bitmap,
                                  const D2D1_COLOR_F& textColor,
                                  float gamma)
    {
        (void)gamma;
        if (!pRT || bitmap.data.empty()) return false;

        // Colore del testo in spazio lineare
        float linR = sRGBToLinear(static_cast<uint8_t>(std::clamp(textColor.r, 0.0f, 1.0f) * 255.0f + 0.5f));
        float linG = sRGBToLinear(static_cast<uint8_t>(std::clamp(textColor.g, 0.0f, 1.0f) * 255.0f + 0.5f));
        float linB = sRGBToLinear(static_cast<uint8_t>(std::clamp(textColor.b, 0.0f, 1.0f) * 255.0f + 0.5f));

        std::vector<uint8_t> colorized(bitmap.data.size());

        // D2D COMPOSITING: Generate a premultiplied alpha bitmap for Direct2D rendering.
        for (int row = 0; row < bitmap.height; ++row)
        {
            for (int col = 0; col < bitmap.width; ++col)
            {
                int offset = row * bitmap.pitch + col * 4;
                const uint8_t* srcPx = bitmap.data.data() + offset;
                uint8_t* dstPx = colorized.data() + offset;

                if (srcPx[3] == 0)
                {
                    dstPx[0] = dstPx[1] = dstPx[2] = dstPx[3] = 0;
                    continue;
                }

                // Maschere di copertura estratte dal filtro
                float maskB = sRGBToLinear(srcPx[0]);
                float maskG = sRGBToLinear(srcPx[1]);
                float maskR = sRGBToLinear(srcPx[2]);

                // Moltiplicazione per il colore del testo
                float outB = linB * maskB;
                float outG = linG * maskG;
                float outR = linR * maskR;

                // Il canale alpha generale è la massima copertura tra i subpixel
                float alphaMask = std::max({maskR, maskG, maskB});

                dstPx[0] = linearToSRGB(outB);
                dstPx[1] = linearToSRGB(outG);
                dstPx[2] = linearToSRGB(outR);
                dstPx[3] = static_cast<uint8_t>(std::clamp(alphaMask, 0.0f, 1.0f) * 255.0f + 0.5f);
            }
        }

        D2D1_BITMAP_PROPERTIES bmpProps = {};
        bmpProps.pixelFormat.format = DXGI_FORMAT_B8G8R8A8_UNORM;
        bmpProps.pixelFormat.alphaMode = D2D1_ALPHA_MODE_PREMULTIPLIED;
        pRT->GetDpi(&bmpProps.dpiX, &bmpProps.dpiY);

        ID2D1Bitmap* pBitmap = nullptr;
        D2D1_SIZE_U bmpSize = {static_cast<UINT32>(bitmap.width), static_cast<UINT32>(bitmap.height)};

        // Correctly pass pointer to bitmap properties for D2D resource creation.
        HRESULT hr = pRT->CreateBitmap(bmpSize, colorized.data(), static_cast<UINT32>(bitmap.pitch), &bmpProps,
                                       &pBitmap);

        if (FAILED(hr) || !pBitmap) return false;

        D2D1_RECT_F destRect = {x, y, x + static_cast<float>(bitmap.width), y + static_cast<float>(bitmap.height)};
        pRT->DrawBitmap(pBitmap, destRect, 1.0f, D2D1_BITMAP_INTERPOLATION_MODE_NEAREST_NEIGHBOR);
        pBitmap->Release();

        return true;
    }
}